### ISSUE TITLE
lean源码编译失败

### ISSUE THREAD

**Issue by firkerword** [gdy666/luci-app-lucky#1]
![IMG_20230102_071156_735](https://user-images.githubusercontent.com/61251923/210187131-e0ab46d7-b437-4cd8-8409-ce3b8c4d0727.jpg)
lean-lede X86-64 1月1号的源码，编译语言包时不通过，试了两次都不行😅

**Comment by gdy666** [comment]
![Screenshot_2023-01-02-10-14-16-390_com mmbox xbrowser pro](https://user-images.githubusercontent.com/2849711/210190959-7e48e979-9747-458d-8456-91eb5dfaa69f.jpg)
你把这个文件删除了再编译试试

**Comment by firkerword** [comment]
> ![Screenshot_2023-01-02-10-14-16-390_com mmbox xbrowser pro](https://user-images.githubusercontent.com/2849711/210190959-7e48e979-9747-458d-8456-91eb5dfaa69f.jpg) 你把这个文件删除了再编译试试

可以了，谢谢大佬
