### ISSUE TITLE
编译了个潘多拉固件上lucky的 ipk,运行出错

### ISSUE THREAD

**Issue by 725216** [gdy666/luci-app-lucky#4]
搜了以下恩山论坛的帖子,可能是mipsel架构的upx压缩的问题,请问怎么在编译的时候不压缩ipk?

https://www.right.com.cn/forum/forum.php?mod=viewthread&tid=8243984&highlight=lucky
![360截图20230319143426268](https://user-images.githubusercontent.com/22210790/226227082-62790064-97ed-4462-a0fb-381c9578ad4c.jpg)
![6](https://user-images.githubusercontent.com/22210790/226227104-d387f027-47af-4d41-9480-2d2eb68506a3.jpg)
![3](https://user-images.githubusercontent.com/22210790/226227129-7d7a2a32-5b07-4e08-aec5-4b6e63117dda.jpg)
![2](https://user-images.githubusercontent.com/22210790/226227150-68d938c4-3659-49d1-9af8-4234f16e86de.jpg)
![5](https://user-images.githubusercontent.com/22210790/226227111-f11f9353-ebaf-461f-8219-7dd1f714848d.jpg)

**Comment by gdy666** [comment]
UPX的问题早在新版upx中解决了
你图中的问题像是你的路由器未开启upnp?

**Comment by gdy666** [comment]
是了，你运行在路由器是不需要打开nat-pmp开关的，打开那个防火墙自动放行开关就性。

**Comment by 725216** [comment]
> 是了，你运行在路由器是不需要打开nat-pmp开关的，打开那个防火墙自动放行开关就性。
怎么打开?

**Comment by gdy666** [comment]
nat-pmp开关的上面那个开关
