### ISSUE TITLE
nat-pmp开关的上面那个开关

### ISSUE THREAD

**Issue by 725216** [gdy666/luci-app-lucky#5]
nat-pmp开关的上面那个开关

_Originally posted by @gdy666 in https://github.com/gdy666/luci-app-lucky/issues/4#issuecomment-1475508610_
            我在上级路由上安装了luci-app-upnp后有了,还需不需要在光猫上设置?现在还是没有获取地址,是不是设置问题?
![d](https://user-images.githubusercontent.com/22210790/226232242-db56af44-9f3b-44d1-a038-0681f5204ccc.jpg)
![b](https://user-images.githubusercontent.com/22210790/226232264-e153dd50-fcdd-4746-8a26-f2b4bd476785.jpg)
![c](https://user-images.githubusercontent.com/22210790/226232275-72f540ae-69ba-4b4b-aa9c-a1c25ded5b9b.jpg)

**Comment by gdy666** [comment]
每个人网络环境不一样，STUN有问题请加Q群和网友谈论，issue只解答软件BUG相关内容。
