### ISSUE TITLE
openwrt_iStoreOS安装ipk 所有设置都是空白，无效！

### ISSUE THREAD

**Issue by ceozero** [gdy666/luci-app-lucky#7]
iStoreOS 21.02.3 2023042111 
opkg 安装了
luci-app-lucky_1.2.3-8_all.ipk
luci-i18n-lucky-zh-cn_1.2.3-8_all.ipk
lucky_1.10.3_Openwrt_x86_64_xiaojv.ipk
安装没有出错，运行也没有出错，进后台的所有设置都是空白，
重启也没有好转，openwrt日志正常，lucky日志正常。
手动升级linux包[lucky_1.10.8_Linux_x86_64_xiaojv.tar.gz](https://github.com/gdy666/lucky/releases/download/v1.10.8/lucky_1.10.8_Linux_x86_64_xiaojv.tar.gz) 还是一样的问题。

我只用了端口转发功能，所以对我暂时没有很大的影响。

**最后发现是网页调用googlesyndication.com被干掉了。。还有两个ads被广告屏蔽软件给干掉了。。。**
![image](https://user-images.githubusercontent.com/22513657/235674811-8ef1e466-bb69-44dc-8ab9-086d7e53dbb2.png)

![image](https://user-images.githubusercontent.com/22513657/235671654-983fcf7b-37bc-4d50-9e35-0de8ade5c72e.png)
![image](https://user-images.githubusercontent.com/22513657/235671695-69fd04fd-ee51-4abc-9c4c-c264df46b2c8.png)
![image](https://user-images.githubusercontent.com/22513657/235671834-2b2b0039-b6e9-4369-943f-d18b207cdc93.png)
![1683032059744](https://user-images.githubusercontent.com/22513657/235672031-763d5f5f-3d77-4c88-b97f-e37981750054.png)
![1683032074790](https://user-images.githubusercontent.com/22513657/235672081-062f4d3f-8bac-4345-a682-78a2546b8bc8.png)
![image](https://user-images.githubusercontent.com/22513657/235671137-4514ea0e-8e5e-450d-9be2-dc12722d52a3.png)

**Comment by gdy666** [comment]
感谢反馈，我这边没发现设置空白的问题，我查一下。。。
